FROM node:12-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install -g @angular/cli@8.0.1

RUN npm install

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
